name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: AWS CLI
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Deploy to Lambda
      working-directory: webapi
      run: dotnet lambda deploy-serverless --stack-name lb-webapi --s3-bucket s3-lambda-repo77 --region eu-west-2
    
